---
title: "P8105 Midterm"
author: "Nick Williams"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)

theme_set(theme_bw())
```

## Importing data

```{r importing data, message = FALSE}
accel_data <- read_csv("./data/p8105_mtp_data.csv") %>% 
  janitor::clean_names()
```

## Cleaning data

```{r normalize or tidy data and creating an hour variable}
accel_data <- accel_data %>% 
  gather(key = "minute", value = "activity_count", activity_1:activity_1440) %>% 
  separate(minute, into = c("drop", "minute"), sep = "_") %>% 
  select(-drop) %>% 
  mutate(day = as_factor(day), 
         day = fct_relevel(day, c("Sunday", "Monday", "Tuesday", "Wednesday", 
                                  "Thursday", "Friday", "Saturday")),
         minute = as.integer(minute), 
         hour = cut(minute, breaks = c(-Inf, 61, 121, 181, 241, 301, 361, 
                                       421, 481, 541, 601, 661, 721, 781, 
                                       841, 901, 961, 1021, 1081, 1141, 1201, 
                                       1261, 1321, 1381, 1441), 
                    labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 
                               13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)
         )
  )
```

### Exploratory analyses plots
  
```{r median activity by day and hour, fig.asp = .7, out.width = "75%", fig.align = "center", dpi = 300}
med_actvty_all_days <- accel_data %>% #add this line to next plot
  group_by(hour) %>% 
  summarize(med_activity = median(activity_count)) %>% 
  mutate(day = as.factor("All days"), 
         hour = as.double(hour))

accel_data %>% 
  mutate(hour = as.double(hour)) %>% 
  group_by(hour, day) %>% 
  summarize(med_activity = median(activity_count)) %>% 
  ggplot(aes(x = hour, y = med_activity, color = day)) +
  geom_line(size = 1, alpha = 0.5) + 
  geom_line(data = med_actvty_all_days, lty = "dashed", size = 1.5) + 
  viridis::scale_color_viridis(name = "Day of the week", 
                               discrete = TRUE, 
                               breaks = c("All days", "Sunday", "Monday", "Tuesday",
                                          "Wednesday", "Thursday", "Friday", "Saturday")) + 
  scale_x_continuous(limits = c(0, 24), 
                     breaks = c(0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24)) + 
  scale_y_continuous(minor_breaks = seq(0, 300, 25)) + 
  labs(title = "Activity count throughout the day stratified by day of the week",
       x = "Hour of the Day (24 hour clock)", 
       y = "Median Activity Count", 
       caption = "Data provided by Jeff Goldsmith, PhD") + 
  theme(legend.position = c(.05, 1), 
        legend.justification = c(0, 1.1), 
        legend.key.size = unit(.1, "in"),
        legend.title = element_text(size = 10), 
        legend.background = element_blank(), 
        legend.box.background = element_rect(color = "black"))
```


```{r plotting the mean and median activity count across weeks by day, warning = FALSE, message = FALSE, fig.align = "center", fig.width = 10, fig.asp = .6, out.width = "100%", dpi = 300}
med_actvty_week_day <- accel_data %>% 
  group_by(week, day) %>% 
  summarize(med_actvty = median(activity_count)) %>% 
  ggplot(aes(x = week, y = med_actvty)) + 
  facet_grid(~ day) + 
  geom_line() + 
  labs(y = "Median Activity Count") +
  geom_smooth(color = "#A35E60", size = 1, se = FALSE) + 
  scale_y_continuous(limits = c(0, 400)) + 
  theme(strip.background = element_blank(),
        strip.text = element_text(color = "black"),
        axis.text.x = element_blank(), 
        axis.title.x = element_blank()
  )

mean_actvty_week_day <- accel_data %>% 
  group_by(week, day) %>% 
  summarize(mean_actvty = mean(activity_count)) %>% 
  ggplot(aes(x = week, y = mean_actvty)) + 
  facet_grid(~ day) + 
  geom_line() + 
  labs(x = "Week", 
       y = "Mean Activity Count") + 
  geom_smooth(color = "#A35E60", se = FALSE) + 
  theme(strip.background = element_blank(), 
        strip.text = element_blank())

wrap_elements(med_actvty_week_day / mean_actvty_week_day) + 
  ggtitle("Median and mean activity count over time stratified by the day of the week")
```




